language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - alias composer="php /usr/bin/composer"
    - composer require --dev satooshi/php-coveralls:dev-master
    - composer install

after_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'


script:
    - vendor/bin/phpunit --coverage-text
