language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - alias composer="php /usr/bin/composer"
    - composer require --dev satooshi/php-coveralls:dev-master
    - composer install

after_script:
    - php vendor/bin/coveralls -v

script:
    - vendor/bin/phpunit --coverage-text
